import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { Lato } from 'next/font/google'

const lato = Lato({ weight: "400", subsets: ['latin'], preload: true })

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Journey Tech Test</title>
        <meta name="description" content="Generated by Journey Tech Test" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${lato.className}`}>
        <Component {...pageProps} />
      </main>
    </>
  )
}
